#+title: BDSCOD

This repository contains an implementation of the approximate likelihood of a
birth-death process with various observation processes described [[https://doi.org/10.1101/2020.10.21.349068][here]]. For a
description of the code that generated the figures in that manuscript see [[file:./examples/README.org::*Paper figures][here]].
An overview of the organisation of the code in this repository is given below.

* Architecture

The diagram below shows the main source and documentation files in this
repository. The computation is split up into several /examples/, for more
details on the examples see the [[file:./examples/README.org][README]]. The main directories are

- =src= which contains the library code which implements the likelihood
  calculation, ie the code you might want to look at if you wanted to apply the
  method to your own data,
- =apps= which contains the application code for each example, ie the code
  specific to the examples presented in the manuscript linked above,
  + The =mcmc= application can be used to run an analysis from the command line
    with data and configuration read from a single JSON file.
- and =examples= which contains the documentation and scripts needed to run each
  example, ie the scripts you will need to run on your machine to replicate the
  results.
  + The =ape-simulation= example is particularly important, it includes the
    script =ape-sim.R= which provides a wrapper around some R packages to make
    it easier to simulate suitable datasets.

[[.repo-diagram.svg]]

* Acknowledgements

- This project was done in collaboration with my co-authors: [[https://github.com/laduplessis][Louis du Plessis]],
  [[https://github.com/kpzoo][Kris V. Parag]], and [[https://en.wikipedia.org/wiki/Oliver_Pybus][Oliver G. Pybus]].
- Thank you to Yunjun Zhang from Peking University for reading through and
  helping to improve documentation.
