## This script demonstrates how to simulate an epidemic using ape and then to
## extract all the event times needed for the likelihood.
library(ggplot2)
library(ggtree)
library(cowplot)
library(treeio)
library(tidytree)
library(tibble)
library(ape)
set.seed(1)


## parameters we care about
params <- list(
 birthRate = 0.228,
 deathRate = 0.026,
 samplingRate = 0.048,
 occurrenceRate = 0.026,
 duration = 30
)

## it will be useful to have some other ways to talk about the parameters so we
## compute a couple of other views.
net_rem_rate <- params$deathRate + params$samplingRate + params$occurrenceRate
net_per_capita_event_rate <- params$birthRate + net_rem_rate
sampling_prob <- params$samplingRate / net_rem_rate
occurrence_prob <- params$occurrenceRate / net_rem_rate
prob_observed <- sampling_prob + occurrence_prob
prob_sampled_given_observed <- sampling_prob / prob_observed

## because the trees generated by rlineage start from the TMRCA we need to
## simulate the length of the root first and subtract this from the duration.
tmrca <- rexp(n = 1, rate = net_per_capita_event_rate)
phy <- rlineage(
  params$birthRate,
  net_rem_rate,
  Tmax = params$duration - tmrca,
  eps = 1e-6
)


## generate a figure showing the complete birth-death tree; a dashed line is
## used to indicate the origin time of the tree.
tr <- treedata(phylo = phy)
plt1 <- ggplot(tr, mapping = aes(x, y)) +
  geom_tree() +
  geom_vline(xintercept = -tmrca, linetype = "dashed") +
  geom_tippoint(size = 1)

## the number of tips in the simulation including extant lineages.
tip_labels <- phy$tip.label
num_tips <- length(tip_labels)
tip_ix <- seq.int(num_tips)
tip_times <- head(node.depth.edgelength(phy), num_tips)

## we can find the tips that are still extant in the simulation
extant_mask <- tip_times + tmrca == params$duration

extant_labels <- tip_labels[extant_mask]
extinct_labels <- tip_labels[!extant_mask]
num_extinct <- length(extinct_labels)

num_observed <- rbinom(n = 1, size = num_extinct, prob = prob_observed)
num_sampled <- rbinom(n = 1, size = num_observed, prob = prob_sampled_given_observed)

observed_labels <- sample(x = extinct_labels, size = num_observed, replace = FALSE)
sampling_labels <- sample(x = observed_labels, size = num_sampled, replace = FALSE)

occurrence_labels <- setdiff(observed_labels, sampling_labels)
num_occurrences <- length(occurrence_labels)

unobserved_labels <- setdiff(extinct_labels, observed_labels)




## It would be useful to have a figure showing these the tree with each tip
## colour coded to indicate its outcome
outcome <- character(num_tips)
for (ix in tip_ix) {
  tl <- tip_labels[ix]
  outcome[ix] <-
    if (is.element(tl, extant_labels)) {
      "extant"
    } else if (is.element(tl, unobserved_labels)) {
      "death"
    } else if  (is.element(tl, sampling_labels)) {
      "sampling"
    } else if (is.element(tl, occurrence_labels)) {
      "occurrence"
    } else {
      stop("unaccounted for tip: ", tl)
    }
}

is_observed <- is.element(outcome, c("sampling", "occurrence"))

tip_annotations <- tibble(
node = tip_ix,
outcome = outcome,
is_observed = is_observed
)

tr <- treedata(phylo = phy, data = tip_annotations)

## Let's make that colour coded figure.
plt2 <- ggplot(tr, mapping = aes(x, y)) +
  geom_tree() +
  geom_tippoint(mapping = aes(colour = outcome),
                size = 5) +
  geom_vline(xintercept = -tmrca, linetype = "dashed") +
  labs(colour = "Tip outcome") +
  theme_tree2(legend.position = "top")


## now we want to extract just the reconstructed tree.
rt <- keep.tip(phy, sampling_labels)
rt_tip_and_node_depths <- node.depth.edgelength(rt)
rt_tip_depths <- head(rt_tip_and_node_depths, num_sampled)
rt_node_depths <- tail(rt_tip_and_node_depths, -num_sampled)

## because the keep.tip function sets the TMRCA to be zero we loose the absolute
## time here so we need to figure out how to adjust this correctly.
true_first_sample_time <- min(tip_times[outcome == "sampling"])
depth_first_in_rt <- min(rt_tip_depths)
rt_offset <- true_first_sample_time - depth_first_in_rt

## we should put all of the observed events into a single data frame so that we
## have them all in a single place.
event_times_df <- data.frame(
time = c(-tmrca, tip_times[outcome == "occurrence"], tip_times[outcome == "sampling"], rt_node_depths + rt_offset),
event = c("origin", rep(c("occurrence", "sampling", "birth"), times = c(num_occurrences, num_sampled, num_sampled - 1)))
)

plt3 <- ggplot(rt, mapping = aes(x, y)) +
  geom_tree() +
  geom_tippoint() +
  geom_vline(xintercept = c(-tmrca - rt_offset, params$duration - tmrca - rt_offset),
             linetype = "dashed") +
  geom_vline(data = event_times_df, 
             mapping = aes(xintercept = time - rt_offset, colour = event)) +
  theme_tree2(legend.position = "top")

duration_measurement_1 <- max(tip_times[outcome == "sampling"]) + tmrca
duration_measurement_2 <- max(rt_tip_depths) + rt_offset + tmrca
## these should be equal up to numerical error.
stopifnot(abs(duration_measurement_1 - duration_measurement_2) < 1e-10 * params$duration)
duration_measurement_3 <- max(tip_times[outcome != "extant"]) + tmrca
## these should be equal up to the the difference in time between the last
## observation and the end of the simulation
stopifnot(abs(duration_measurement_1 - params$duration) < 0.05 * params$duration)

## we can re-generate a previous plot now using the event_times_df to make sure
## we have eveything correct.
plt4 <- ggplot(tr, mapping = aes(x, y)) +
  geom_tippoint(mapping = aes(colour = outcome, shape = is_observed),
                size = 3) +
  geom_nodepoint() +
  geom_vline(data = event_times_df, aes(xintercept = time, colour = event)) +
  geom_tree() +
  labs(colour = "Tip outcome",
       shape = "Observed") +
  theme_tree2(legend.position = "top")


## finally we cant write the times to CSV for use elsewhere
write.table(x = event_times_df,
            file = "ape-simulation-event-times.csv",
            sep = ",",
            row.names = FALSE)


## Since we know the distribution of the number of each type of extinction event
## given the total number of extinctions we can generate a plot to check this is
## correct.
hist_plt_df <- data.frame(
outcome = c("death",
            "sampling",
            "occurrence"),
empirical = c(num_extinct - num_observed,
              num_sampled,
              num_occurrences),
theory = c(qbinom(p = 0.5, size = num_extinct, prob = 1 - sampling_prob - occurrence_prob),
           qbinom(p = 0.5, size = num_extinct, prob = sampling_prob),
           qbinom(p = 0.5, size = num_extinct, prob = occurrence_prob)),
theory_min = c(qbinom(p = 0.025, size = num_extinct, prob = 1 - sampling_prob - occurrence_prob),
               qbinom(p = 0.025, size = num_extinct, prob = sampling_prob),
               qbinom(p = 0.025, size = num_extinct, prob = occurrence_prob)),
theory_max = c(qbinom(p = 0.975, size = num_extinct, prob = 1 - sampling_prob - occurrence_prob),
               qbinom(p = 0.975, size = num_extinct, prob = sampling_prob),
               qbinom(p = 0.975, size = num_extinct, prob = occurrence_prob))
)

plt5 <- ggplot(hist_plt_df) +
  geom_col(mapping = aes(x = outcome, y = empirical)) +
  geom_point(mapping = aes(x = outcome, y = theory)) +
  geom_errorbar(mapping = aes(x = outcome, ymin = theory_min, ymax = theory_max)) +
  labs(y = "count") +
  theme_classic()

plt <- plot_grid(plt4, plt5, nrow = 1, rel_widths = c(2,1))

ggsave(
  filename = "ape-simulation-figure.png",
  plot = plt,
  width = 25,
  height = 15,
  units = "cm"
)
