#+title: Examples

* Examples

There are a couple of simulation studies. See the following files for details.

** Prevalence CI Calibration

Generates point estimates and credible intervals for a set of simulations and
looks at the bias in the point estimates and the coverage of the credible
intervals. This is useful for assessing the utility of the approximation.

** Simulation Study Aggregated Observations

Explores how much information is lost when the data is aggregated, ie when
multiple unscheduled observations are aggregated into a single observation and
treated as a scheduled observation. This is useful for assessing the impact of
model misspecification.

** Simulating data with =ape=

** Timing Evaluation

Generates the figures in which the log-likelihood function is compared to
existing methods both in terms of the values calculated and the computational
complexity. This is useful for assessing the potential to use this likelihood in
practise on large datasets.

* Parameters

In =aggregated-observations=, =ci-calibration= and =timing-evaluation= a common
set of parameters are used for the unscheduled events. These values are stored
in =example-parameters.json= so they can be read from a single source.

#+INCLUDE: "example-parameters.json" src emacs-lisp

The parameters used come from [[https://doi.org/10.1101/2020.09.12.20193284][Vaughan /et al/ (2020)]] which estimated \(R_0\) for
several outbreaks of SARS-CoV-2 early on in the pandemic. Only genomic data was
used in this analysis so a minor adjustment has been made to allow for the
possibility of occurrence data.

** Calculation

The largest outbreak considered by [[https://doi.org/10.1101/2020.09.12.20193284][Vaughan /et al/ (2020)]] occurred in WA State
(USA) and consisted of 217 sequences sampled over 20 days. Their analysis
assumed an average infectious duration of 10 days. Using [[https://automeris.io/WebPlotDigitizer/][WebPlotDigitizer V4.5]]
we extracted the values of \(R_0\) and the sampling proportion associated with
this outbreak which were 2.28 and 0.48 respectively. We add the assumption that
half of the unsequenced cases are occurrences. The calculation makes use of the
following equations assuming we are working in units of days. From the average
duration of being infectious we have

\[
\mu + \psi + \omega = \frac{1}{10}.
\]

From the extracted values we have

\[
R_0 = \frac{\lambda}{\mu + \psi + \omega} = 2.28
\]

and

\[
\frac{\psi}{\mu + \psi + \omega} = 0.48.
\]

The assumption that half the unsampled infections are occurrences gives us

\[
\mu = \psi
\]

** Prior distribution

The prior distribution used by Vaughan /et al/ is \(\text{LogNormal}(0.8,0.5)\)
on \(R_0\). This comes very close to putting \(95\%\) of the prior probability
between 1 and 6. The prior on the sampling proportion was \(\text{Beta}(1,4)\)
which puts approximately \(95\%\) of the prior probability on values below
\(0.6\). To move between prior distributions we need the Jacobian though which
is

\[
\frac{1}{\alpha^2 (\alpha - \psi)}
\]

where \(\alpha\) is \(0.1\) when the expected time until uninfectious is ten
days.

#+header: :exports results
#+begin_src maxima :tangle vaughan.mac
declare(λ, real);
declare(μ, real);
declare(ψ, real);
declare(ω, real);

assume(λ > 0);
assume(μ > 0);
assume(ψ > 0);
assume(ω > 0);


exp1 : abs(
  determinant(
    jacobian(
      [ψ / (α), λ / (α), ω / (α - ψ)], [λ, ψ, ω]
      )
    )
  );

exp2 : abs((1 / α^2) / (α - ψ));

print(is(equal(exp1, exp2)));
#+end_src

#+RESULTS:
: true

#+begin_src bibtex
@article{vaughan2020estimates,
  author =       {Vaughan, Timothy G and Scir{\'e}, J{\'e}r{\'e}mie and Nadeau,
                  Sarah A and Stadler, Tanja},
  title =        {{Estimates of outbreak-specific SARS-CoV-2 epidemiological
                  parameters from genomic data}},
  year =         2020,
  doi =          {10.1101/2020.09.12.20193284},
  publisher =    {Cold Spring Harbor Laboratory Press},
  URL =
                  {https://www.medrxiv.org/content/early/2020/09/14/2020.09.12.20193284},
  journal =      {medRxiv}
}

@misc{Rohatgi2020,
  url = {https://automeris.io/WebPlotDigitizer},
  author = {Rohatgi, Ankit},
  title = {Webplotdigitizer: Version 4.5},
  year = {2021}
}
#+end_src

