#+title: Examples

* Examples

There are a couple of simulation studies. See the following files for details.

** Prevalence CI Calibration

Generates point estimates and credible intervals for a set of simulations and
looks at the bias in the point estimates and the coverage of the credible
intervals. This is useful for assessing the utility of the approximation.

** Simulation Study Aggregated Observations

Explores how much information is lost when the data is aggregated, ie when
multiple unscheduled observations are aggregated into a single observation and
treated as a scheduled observation. This is useful for assessing the impact of
model misspecification.

** Simulating data with =ape=

** Timing Evaluation

Generates the figures in which the log-likelihood function is compared to
existing methods both in terms of the values calculated and the computational
complexity. This is useful for assessing the potential to use this likelihood in
practise on large datasets.

* Parameters

In =aggregated-observations=, =ci-calibration= and =timing-evaluation= a common
set of parameters are used for the unscheduled events. These values are stored
in =example-parameters.json= so they can be read from a single source.

#+INCLUDE: "example-parameters.json" src emacs-lisp

The parameters used come from [[https://doi.org/10.1101/2020.09.12.20193284][Vaughan /et al/ (2020)]] which estimated \(R_0\) for
several outbreaks of SARS-CoV-2 early on in the pandemic. Only genomic data was
used in this analysis so a minor adjustment has been made to allow for the
possibility of occurrence data.

#+begin_src bibtex
@article{vaughan2020estimates,
  author =       {Vaughan, Timothy G and Scir{\'e}, J{\'e}r{\'e}mie and Nadeau,
                  Sarah A and Stadler, Tanja},
  title =        {{Estimates of outbreak-specific SARS-CoV-2 epidemiological
                  parameters from genomic data}},
  year =         2020,
  doi =          {10.1101/2020.09.12.20193284},
  publisher =    {Cold Spring Harbor Laboratory Press},
  URL =
                  {https://www.medrxiv.org/content/early/2020/09/14/2020.09.12.20193284},
  journal =      {medRxiv}
}

@misc{Rohatgi2020,
  url = {https://automeris.io/WebPlotDigitizer},
  author = {Rohatgi, Ankit},
  title = {Webplotdigitizer: Version 4.5},
  year = {2021}
}
#+end_src

