#+title: Examples

* Examples

There are a couple of simulation studies. See the following files for details.

** Prevalence CI Calibration

Generates point estimates and credible intervals for a set of simulations and
looks at the bias in the point estimates and the coverage of the credible
intervals. This is useful for assessing the utility of the approximation.

** Simulation Study Aggregated Observations

Explores how much information is lost when the data is aggregated, ie when
multiple unscheduled observations are aggregated into a single observation and
treated as a scheduled observation. This is useful for assessing the impact of
model misspecification.

** Timing Evaluation

Generates the figures in which the log-likelihood function is compared to
existing methods both in terms of the values calculated and the computational
complexity. This is useful for assessing the potential to use this likelihood in
practise on large datasets.

* Parameters

In =aggregated-observations=, =ci-calibration= and =timing-evaluation= a common
set of parameters are used for the unscheduled events. These values are stored
in =example-parameters.json= so they can be read from a single source.

#+INCLUDE: "example-parameters.json" src emacs-lisp
