* Simulation Study of Aggregated Observations

This simulation study looks at the loss of information when unscheduled
observations are aggregated into scheduled observations at pre-determined times.
MCMC is used to explore the posterior distribution of the parameters under the
simulated data and another data set generated by aggregating unscheduled
observations into scheduled observations.

** Running the simulation study

The running of this simulation study is coordinated by the script =run.sh=.
There are three steps to the simulation study: 1) make a JSON configuration file
for the simulation study, 2) run the application code with the JSON file, and 3)
generate some visualisations of the results.

*** Parameters

This uses the parameters specified in =bdscod/example/example-parameters.json=
for the rates of unscheduled events. The timings of the scheduled events in and
the configuration of the MCMC are hard coded in the =src/make-json-config.R=
script. The R script =make-json-config.R= produces the JSON configuration file
and provides a cleaner way to generate this than writing it by hand.

The code for the application lives in
=bdscod/apps/simulation-study-aggregated-observations/Main.hs=.

The =src/plot.R= script generates all of the figures and writes them to =out/=.
The most interesting figure is =regular-and-aggregated-data.png= which contrasts
the prevalence estimate using the regular and aggregated data and shows a simple
visualisation of these data.

** Output 

The main figures produced from this example are the following:

- =out/aggregated-data-posterior-joints.pdf=
- =out/aggregated-data-posterior-marginals.pdf=
- =out/regular-and-aggregated-data.pdf=
- =out/regular-data-posterior-joints.pdf=
- =out/regular-data-posterior-marginals.pdf=
