* Simulation Study of Aggregated Observations

This simulation study looks at the loss of information when unscheduled data is
aggregated into scheduled observations.

** Running the simulation study

The running of this simulation study is coordinated by the script =run.sh=. The
contents of that file are given below. The simulation study is specified in a
JSON file which is given as a command line argument. The R script
=make-json-config.R= produces this so you don't need to edit it manually.

=run.sh=
#+BEGIN_SRC sh :tangle run.sh
Rscript src/make-json-config.R

stack build
stack exec -- simulation-study-aggregated-observations agg-app-config.json

# Rscript src/plot-simulated-data.R
# Rscript src/plot-llhd-profiles.R
#+END_SRC

** TODO Delete this section when this is finished

Here are some notes to explain what happens =Main.hs=.

- =simulationStudy= runs the simulation in the =Simulation= monad which means
  that it already has all of the configuration data.
- =observeEpidemicThrice= takes a full simulation and returns pairs of inference
  configuration and the accompanying data.
- The function =evaluateLLHD=, =estimateLLHD= and =estimateLLHDAggregated= are
  there to take the observations and computes the cross-sections of the LLHD
  function and the distribution of prevalence and writes these to the files
  pointed at by the given =InferenceConfiguration=.
- =generateLlhdProfileCurves= is the function used to evaluate the
  cross-sections and prevalence distribution and record this to disk.
